pipeline {
  agent none
  parameters {
    string(name: 'BRANCH', defaultValue: 'develop', description: '')
  }
  
  stages {
    stage('Testing') {
       agent {
        label 'built-in'   
       }
      steps {
        script {
          for (label in pullRequest.labels) {
            println(label.matches("(.*)-RT")); 
          } 
          sh 'echo "I ran as expected!"'
        }    
      }
    }
  }
}
